baseURL = "https://lemmysmackett.com/"
languageCode = "en-us"
title = "Lemmy Smackett"
theme = "smackett"

[menu]
  [[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1
    
[taxonomies]
  genre = "genres"
  length = "length"
  tag = "tags"
  erotica_tag = "erotica_tags"
  series = "series"
  mature = "mature"
  extreme = "extreme"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = ["max-age=86400, must-revalidate"]